language: node_js
node_js:
  - '7'
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - export PATH="$PATH:`yarn global bin`"
  - yarn global add @angular/cli
  - yarn global add karma
  - yarn
  - ng build --aot
script: yarn test-ci
after_success: yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: dist/