language: node_js
node_js:
  - '7'
addons:
  apt:
    packages:
    - lftp
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - export PATH="$PATH:`yarn global bin`"
  - yarn global add @angular/cli
  - yarn global add karma
  - yarn
  - ng build --aot
script: yarn test-ci
after_success: yarn build
after_success:
    "lftp -u $FTP_USER,$FTP_PASS $FTP_SITE -e 'mirror -c -e -R dist ~''"
notifications:
    slack: kittentl:moBQCRlnTw615glK6ogAaZ1w