language: node_js
node_js:
  - '7'
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install -g yarn
  - yarn global add @angular/cli
  - yarn global add karma
  - yarn
  - ng build --aot
  - dredd
script: yarn test-ci
before_install:
  - npm install -g dredd@4.7.0
