language: node_js
node_js:
  - '7'
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install -g @angular/cli
  - npm install -g karma
  - npm install
  - ng build --aot
script: npm run test-ci
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
