language: node_js
node_js:
  - '7'
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install -g @angular/cli
  - npm install -g karma
  - npm install
  - ng build --aot
script: npm run test-ci
